# Generated by Django 5.1.4 on 2024-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_order_amount_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
